### PR TITLE
Fix #8 - Updated image2pattern.js and prepImage.js to use node paths module

### LINKED ISSUE #8: Update file paths to use node's path module
Several places read and write files using string concatenation instead of the Path module. The code should be updated project wide to use path.

### PR DESCRIPTION
**Pull request by CometS1**
Added in path.dirname to image2pattern.js variable imageFilePath call, and added path.basename to prepImage.js variable filePath call.

### CODE REVIEW

**Comment by CometS1** [comment]
I removed the platform detection and tested it, it should work fine now on both systems.

**Comment by CometS1** [comment]
I replaced the string concatenation with the path.join and path.resolve function. I had to leave them in the respective path.dirname and path.basename function because it gave an error when left alone. I did not use string concatenation with for the .svg as it seemed to work fine without it. Please take a look and tell me if that's the way you wanted this issue to be solved or if you want any other changes.

**Comment by acrosman** [comment]
I'm going to go ahead an merge this as is. I'd like to fix a linting issue that would conflict with the PR.

**Comment by CometS1** [comment]
Whenever I try to use the path.join function alone in the way that you showed by replacing the current one, It gives me an error that says that the file already exist even when I make sure that it is not there. You said that it works on your system? I can't figure out why it won't work on my system.

**Comment by acrosman** [comment]
It's possible there is an access issue on the output directory or something similar that means the file cannot be overwritten easily. I'm confident that `join()` is the right answer as using `dirname()` crops off the image file name and throws errors when the application tries to write the file. But I'm sure the app does not sufficiently check file permissions before attempting to write files, and lacks some needed error trapping. 

If you want to update to the most recent version of the project's master branch, run `npm run gen-test` and post any errors as a new issue (along with OS details), I'm happy to dig into them with you.

**Pull request merged**
